[package]
name = "p256_bigcurve"
type = "bin"
authors = [""]

[dependencies]
bignum = { tag = "v0.8.0", git = "https://github.com/noir-lang/noir-bignum" }
bigcurve = { tag = "v0.11.0", git = "https://github.com/noir-lang/noir_bigcurve" }
