[package]
name = "openvm-sha256"
version = "0.1.0"
edition = "2024"

[dependencies]
openvm = { git = "https://github.com/openvm-org/openvm.git", features = ["std"], tag = "v1.4.0" }
openvm-sha2 = { git = "https://github.com/openvm-org/openvm.git" }

[workspace]
