[package]
name = "risc0-sha256-guest"
version = "0.1.0"
edition = "2024"

[dependencies]
risc0-zkvm = { version = "2.2", default-features = false, features = [
    "std",
    "unstable",
] }
sha2 = { git = "https://github.com/risc0/RustCrypto-hashes", tag = "sha2-v0.10.6-risczero.0" }
